'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsChartLyrics
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://api.chartlyrics.com/", ConfigurationName:="wsChartLyrics.apiv1Soap")>  _
    Friend Interface apiv1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/SearchLyric", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SearchLyric(ByVal artist As String, ByVal song As String) As wsChartLyrics.SearchLyricResult()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/SearchLyric", ReplyAction:="*")>  _
        Function SearchLyricAsync(ByVal artist As String, ByVal song As String) As System.Threading.Tasks.Task(Of wsChartLyrics.SearchLyricResult())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/SearchLyricText", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SearchLyricText(ByVal lyricText As String) As wsChartLyrics.SearchLyricResult()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/SearchLyricText", ReplyAction:="*")>  _
        Function SearchLyricTextAsync(ByVal lyricText As String) As System.Threading.Tasks.Task(Of wsChartLyrics.SearchLyricResult())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/GetLyric", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetLyric(ByVal lyricId As Integer, ByVal lyricCheckSum As String) As wsChartLyrics.GetLyricResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/GetLyric", ReplyAction:="*")>  _
        Function GetLyricAsync(ByVal lyricId As Integer, ByVal lyricCheckSum As String) As System.Threading.Tasks.Task(Of wsChartLyrics.GetLyricResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/AddLyric", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AddLyric(ByVal trackId As Integer, ByVal trackCheckSum As String, ByVal lyric As String, ByVal email As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/AddLyric", ReplyAction:="*")>  _
        Function AddLyricAsync(ByVal trackId As Integer, ByVal trackCheckSum As String, ByVal lyric As String, ByVal email As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/SearchLyricDirect", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SearchLyricDirect(ByVal artist As String, ByVal song As String) As wsChartLyrics.GetLyricResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.chartlyrics.com/SearchLyricDirect", ReplyAction:="*")>  _
        Function SearchLyricDirectAsync(ByVal artist As String, ByVal song As String) As System.Threading.Tasks.Task(Of wsChartLyrics.GetLyricResult)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://api.chartlyrics.com/")>  _
    Partial Public Class SearchLyricResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private trackChecksumField As String
        
        Private trackIdField As Integer
        
        Private lyricChecksumField As String
        
        Private lyricIdField As Integer
        
        Private songUrlField As String
        
        Private artistUrlField As String
        
        Private artistField As String
        
        Private songField As String
        
        Private songRankField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property TrackChecksum() As String
            Get
                Return Me.trackChecksumField
            End Get
            Set
                Me.trackChecksumField = value
                Me.RaisePropertyChanged("TrackChecksum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property TrackId() As Integer
            Get
                Return Me.trackIdField
            End Get
            Set
                Me.trackIdField = value
                Me.RaisePropertyChanged("TrackId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property LyricChecksum() As String
            Get
                Return Me.lyricChecksumField
            End Get
            Set
                Me.lyricChecksumField = value
                Me.RaisePropertyChanged("LyricChecksum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property LyricId() As Integer
            Get
                Return Me.lyricIdField
            End Get
            Set
                Me.lyricIdField = value
                Me.RaisePropertyChanged("LyricId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property SongUrl() As String
            Get
                Return Me.songUrlField
            End Get
            Set
                Me.songUrlField = value
                Me.RaisePropertyChanged("SongUrl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ArtistUrl() As String
            Get
                Return Me.artistUrlField
            End Get
            Set
                Me.artistUrlField = value
                Me.RaisePropertyChanged("ArtistUrl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Artist() As String
            Get
                Return Me.artistField
            End Get
            Set
                Me.artistField = value
                Me.RaisePropertyChanged("Artist")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property Song() As String
            Get
                Return Me.songField
            End Get
            Set
                Me.songField = value
                Me.RaisePropertyChanged("Song")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property SongRank() As Integer
            Get
                Return Me.songRankField
            End Get
            Set
                Me.songRankField = value
                Me.RaisePropertyChanged("SongRank")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://api.chartlyrics.com/")>  _
    Partial Public Class GetLyricResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private trackChecksumField As String
        
        Private trackIdField As Integer
        
        Private lyricChecksumField As String
        
        Private lyricIdField As Integer
        
        Private lyricSongField As String
        
        Private lyricArtistField As String
        
        Private lyricUrlField As String
        
        Private lyricCovertArtUrlField As String
        
        Private lyricRankField As Integer
        
        Private lyricCorrectUrlField As String
        
        Private lyricField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property TrackChecksum() As String
            Get
                Return Me.trackChecksumField
            End Get
            Set
                Me.trackChecksumField = value
                Me.RaisePropertyChanged("TrackChecksum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property TrackId() As Integer
            Get
                Return Me.trackIdField
            End Get
            Set
                Me.trackIdField = value
                Me.RaisePropertyChanged("TrackId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property LyricChecksum() As String
            Get
                Return Me.lyricChecksumField
            End Get
            Set
                Me.lyricChecksumField = value
                Me.RaisePropertyChanged("LyricChecksum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property LyricId() As Integer
            Get
                Return Me.lyricIdField
            End Get
            Set
                Me.lyricIdField = value
                Me.RaisePropertyChanged("LyricId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property LyricSong() As String
            Get
                Return Me.lyricSongField
            End Get
            Set
                Me.lyricSongField = value
                Me.RaisePropertyChanged("LyricSong")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property LyricArtist() As String
            Get
                Return Me.lyricArtistField
            End Get
            Set
                Me.lyricArtistField = value
                Me.RaisePropertyChanged("LyricArtist")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property LyricUrl() As String
            Get
                Return Me.lyricUrlField
            End Get
            Set
                Me.lyricUrlField = value
                Me.RaisePropertyChanged("LyricUrl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property LyricCovertArtUrl() As String
            Get
                Return Me.lyricCovertArtUrlField
            End Get
            Set
                Me.lyricCovertArtUrlField = value
                Me.RaisePropertyChanged("LyricCovertArtUrl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property LyricRank() As Integer
            Get
                Return Me.lyricRankField
            End Get
            Set
                Me.lyricRankField = value
                Me.RaisePropertyChanged("LyricRank")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property LyricCorrectUrl() As String
            Get
                Return Me.lyricCorrectUrlField
            End Get
            Set
                Me.lyricCorrectUrlField = value
                Me.RaisePropertyChanged("LyricCorrectUrl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Lyric() As String
            Get
                Return Me.lyricField
            End Get
            Set
                Me.lyricField = value
                Me.RaisePropertyChanged("Lyric")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface apiv1SoapChannel
        Inherits wsChartLyrics.apiv1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class apiv1SoapClient
        Inherits System.ServiceModel.ClientBase(Of wsChartLyrics.apiv1Soap)
        Implements wsChartLyrics.apiv1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SearchLyric(ByVal artist As String, ByVal song As String) As wsChartLyrics.SearchLyricResult() Implements wsChartLyrics.apiv1Soap.SearchLyric
            Return MyBase.Channel.SearchLyric(artist, song)
        End Function
        
        Public Function SearchLyricAsync(ByVal artist As String, ByVal song As String) As System.Threading.Tasks.Task(Of wsChartLyrics.SearchLyricResult()) Implements wsChartLyrics.apiv1Soap.SearchLyricAsync
            Return MyBase.Channel.SearchLyricAsync(artist, song)
        End Function
        
        Public Function SearchLyricText(ByVal lyricText As String) As wsChartLyrics.SearchLyricResult() Implements wsChartLyrics.apiv1Soap.SearchLyricText
            Return MyBase.Channel.SearchLyricText(lyricText)
        End Function
        
        Public Function SearchLyricTextAsync(ByVal lyricText As String) As System.Threading.Tasks.Task(Of wsChartLyrics.SearchLyricResult()) Implements wsChartLyrics.apiv1Soap.SearchLyricTextAsync
            Return MyBase.Channel.SearchLyricTextAsync(lyricText)
        End Function
        
        Public Function GetLyric(ByVal lyricId As Integer, ByVal lyricCheckSum As String) As wsChartLyrics.GetLyricResult Implements wsChartLyrics.apiv1Soap.GetLyric
            Return MyBase.Channel.GetLyric(lyricId, lyricCheckSum)
        End Function
        
        Public Function GetLyricAsync(ByVal lyricId As Integer, ByVal lyricCheckSum As String) As System.Threading.Tasks.Task(Of wsChartLyrics.GetLyricResult) Implements wsChartLyrics.apiv1Soap.GetLyricAsync
            Return MyBase.Channel.GetLyricAsync(lyricId, lyricCheckSum)
        End Function
        
        Public Function AddLyric(ByVal trackId As Integer, ByVal trackCheckSum As String, ByVal lyric As String, ByVal email As String) As String Implements wsChartLyrics.apiv1Soap.AddLyric
            Return MyBase.Channel.AddLyric(trackId, trackCheckSum, lyric, email)
        End Function
        
        Public Function AddLyricAsync(ByVal trackId As Integer, ByVal trackCheckSum As String, ByVal lyric As String, ByVal email As String) As System.Threading.Tasks.Task(Of String) Implements wsChartLyrics.apiv1Soap.AddLyricAsync
            Return MyBase.Channel.AddLyricAsync(trackId, trackCheckSum, lyric, email)
        End Function
        
        Public Function SearchLyricDirect(ByVal artist As String, ByVal song As String) As wsChartLyrics.GetLyricResult Implements wsChartLyrics.apiv1Soap.SearchLyricDirect
            Return MyBase.Channel.SearchLyricDirect(artist, song)
        End Function
        
        Public Function SearchLyricDirectAsync(ByVal artist As String, ByVal song As String) As System.Threading.Tasks.Task(Of wsChartLyrics.GetLyricResult) Implements wsChartLyrics.apiv1Soap.SearchLyricDirectAsync
            Return MyBase.Channel.SearchLyricDirectAsync(artist, song)
        End Function
    End Class
End Namespace
