'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsLooWebPlayerII
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://wsLWP2.org/", ConfigurationName:="wsLooWebPlayerII.wsLWPSoap")>  _
    Public Interface wsLWPSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RefreshCanzoni", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RefreshCanzoni() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RefreshCanzoni", ReplyAction:="*")>  _
        Function RefreshCanzoniAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaYouTube", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaYouTube(ByVal idBrano As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaYouTube", ReplyAction:="*")>  _
        Function RitornaYouTubeAsync(ByVal idBrano As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/ScaricaVideoYouTube", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ScaricaVideoYouTube(ByVal link As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/ScaricaVideoYouTube", ReplyAction:="*")>  _
        Function ScaricaVideoYouTubeAsync(ByVal link As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaProssimoBrano", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaProssimoBrano(ByVal Random As String, ByVal vecchioBrano As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaProssimoBrano", ReplyAction:="*")>  _
        Function RitornaProssimoBranoAsync(ByVal Random As String, ByVal vecchioBrano As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaBranoDaID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaBranoDaID(ByVal Brano As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaBranoDaID", ReplyAction:="*")>  _
        Function RitornaBranoDaIDAsync(ByVal Brano As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaJSON", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaJSON() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/RitornaJSON", ReplyAction:="*")>  _
        Function RitornaJSONAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/CreaRitornaUtenza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreaRitornaUtenza(ByVal Utenza As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/CreaRitornaUtenza", ReplyAction:="*")>  _
        Function CreaRitornaUtenzaAsync(ByVal Utenza As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/ScaricaGIF", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ScaricaGIF(ByVal Artista As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wsLWP2.org/ScaricaGIF", ReplyAction:="*")>  _
        Function ScaricaGIFAsync(ByVal Artista As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsLWPSoapChannel
        Inherits wsLooWebPlayerII.wsLWPSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsLWPSoapClient
        Inherits System.ServiceModel.ClientBase(Of wsLooWebPlayerII.wsLWPSoap)
        Implements wsLooWebPlayerII.wsLWPSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function RefreshCanzoni() As String Implements wsLooWebPlayerII.wsLWPSoap.RefreshCanzoni
            Return MyBase.Channel.RefreshCanzoni
        End Function
        
        Public Function RefreshCanzoniAsync() As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.RefreshCanzoniAsync
            Return MyBase.Channel.RefreshCanzoniAsync
        End Function
        
        Public Function RitornaYouTube(ByVal idBrano As String) As String Implements wsLooWebPlayerII.wsLWPSoap.RitornaYouTube
            Return MyBase.Channel.RitornaYouTube(idBrano)
        End Function
        
        Public Function RitornaYouTubeAsync(ByVal idBrano As String) As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.RitornaYouTubeAsync
            Return MyBase.Channel.RitornaYouTubeAsync(idBrano)
        End Function
        
        Public Function ScaricaVideoYouTube(ByVal link As String) As String Implements wsLooWebPlayerII.wsLWPSoap.ScaricaVideoYouTube
            Return MyBase.Channel.ScaricaVideoYouTube(link)
        End Function
        
        Public Function ScaricaVideoYouTubeAsync(ByVal link As String) As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.ScaricaVideoYouTubeAsync
            Return MyBase.Channel.ScaricaVideoYouTubeAsync(link)
        End Function
        
        Public Function RitornaProssimoBrano(ByVal Random As String, ByVal vecchioBrano As String) As String Implements wsLooWebPlayerII.wsLWPSoap.RitornaProssimoBrano
            Return MyBase.Channel.RitornaProssimoBrano(Random, vecchioBrano)
        End Function
        
        Public Function RitornaProssimoBranoAsync(ByVal Random As String, ByVal vecchioBrano As String) As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.RitornaProssimoBranoAsync
            Return MyBase.Channel.RitornaProssimoBranoAsync(Random, vecchioBrano)
        End Function
        
        Public Function RitornaBranoDaID(ByVal Brano As String) As String Implements wsLooWebPlayerII.wsLWPSoap.RitornaBranoDaID
            Return MyBase.Channel.RitornaBranoDaID(Brano)
        End Function
        
        Public Function RitornaBranoDaIDAsync(ByVal Brano As String) As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.RitornaBranoDaIDAsync
            Return MyBase.Channel.RitornaBranoDaIDAsync(Brano)
        End Function
        
        Public Function RitornaJSON() As String Implements wsLooWebPlayerII.wsLWPSoap.RitornaJSON
            Return MyBase.Channel.RitornaJSON
        End Function
        
        Public Function RitornaJSONAsync() As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.RitornaJSONAsync
            Return MyBase.Channel.RitornaJSONAsync
        End Function
        
        Public Function CreaRitornaUtenza(ByVal Utenza As String) As String Implements wsLooWebPlayerII.wsLWPSoap.CreaRitornaUtenza
            Return MyBase.Channel.CreaRitornaUtenza(Utenza)
        End Function
        
        Public Function CreaRitornaUtenzaAsync(ByVal Utenza As String) As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.CreaRitornaUtenzaAsync
            Return MyBase.Channel.CreaRitornaUtenzaAsync(Utenza)
        End Function
        
        Public Function ScaricaGIF(ByVal Artista As String) As String Implements wsLooWebPlayerII.wsLWPSoap.ScaricaGIF
            Return MyBase.Channel.ScaricaGIF(Artista)
        End Function
        
        Public Function ScaricaGIFAsync(ByVal Artista As String) As System.Threading.Tasks.Task(Of String) Implements wsLooWebPlayerII.wsLWPSoap.ScaricaGIFAsync
            Return MyBase.Channel.ScaricaGIFAsync(Artista)
        End Function
    End Class
End Namespace
